version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - CONFIG_PATH=./.env
# migrations doesn't work, run it manually with golang-migrate migrate -path ./internal/storage/schema -database "postgres://root:root@localhost:5432/cars_catalog?sslmode=disable" up
  db:
    container_name: effective_mobile_db
    image: postgres
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./internal/storage/schema:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: cars_catalog
    ports:
      - "5432:5432"
